version: 0.0
os: linux

files:
  - source: /
    destination: /home/linux/deploy-fe
    overwrite: yes

permissions:
  - object: /home/linux/deploy-fe
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: /deploy.sh
      timeout: 60
      runas: root
