# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI CD

on:
  push:
    branches: ["main"]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
  
        uses: actions/checkout@v2.3.1

    
        run: |
          yarn install --immutable --immutable-cache
          yarn run build
      
     
        uses: awact/s3-action@master
        with:
        args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: "./dist"
          AWS_REGION: "ap-northeast-1"
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}

